### PR TITLE
Radio bug fix

### PR DESCRIPTION
**Pull request by lonhep-tamfeb**
* chat scroll bug fixed
* help menu updated
* storing up to 90 latest chatlogs

### CODE REVIEW

**Comment by hanfel-dovned** [comment]
We were able to reproduce the two bugs described by ~sorreg-namtyv and solve one of them. We also discovered and solved two more on top of that.

**Solved**

- We were able to reproduce the scroll bug: once over 100 chat messages have come in, the UI deletes the oldest messages in order to save memory, which causes newer messages to jump up, making the user lose their place if they aren't scrolled all the way to the bottom of chat. We fixed this by only deleting these messages when the user has scrolled down to the bottom of chat.

- When you refresh the page, only the most recent 16 messages are displayed. This is a jarringly low number that makes it feel like something went wrong; we increased this to 90.

- When you publish a station, sometimes this does not appear in navigation as being published. This is because the existence of a published station is relayed by a centralized ship run by ~bacwyl-samweg, and sometimes this ship has issues. The ultimate solution to this problem is to either run a centralized UF ship that performs this service perfectly, or to decentralize %radio by restructuring it in a more fundamental way (for instance, by letting users publish their stations directly to Earth and let people eauth/MetaMask login to chat). For this initial bug-fix pass, we simply updated the Help pop-up window to explain the !tune command, which lets users directly access a station whether it's visibly published or not.

**In-Progress**

- When the connection between the UI and the user's Urbit ship drops, no new chat messages or page actions (such as the host loading a new video) come in. We plan to fix this by detecting that the connection has dropped and attempting to auto-reconnect; we haven't been able to get this working using the traditional `onError()` urbit/http-api method. ~lonhep-tamfeb is going to keep working on this and is planning on having a solution within a day or two.

**Comment by gtimoth** [comment]
if possible, i would like the increased chatlog size to come with the ability for the host to delete chat messages, and possibly a way to clear the full chatlog. a benefit of the small (16) chatlog was that it made realtime conversations somewhat more private, and users could spam 16 messages to hide older ones.

**Comment by bonbud-macryg** [comment]
@bacwyls What's the highest number of logged messages you'd be cool with if we changed nothing else? I think a higher number like 90 is better and your suggestions are good ones; we can revisit this in another PR.

**Comment by gtimoth** [comment]
90 is ok if you don't want to increase scope, which makes sense!

**Comment by gtimoth** [comment]
LGTM, thank you!

**Pull request merged**
